"""add_url_and_notified_at_to_releases

Revision ID: 964972c7d7fe
Revises: d5480dd3dbfc
Create Date: 2026-07-11 21:55:03.705345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964972c7d7fe'
down_revision: Union[str, Sequence[str], None] = 'd5480dd3dbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('url', sa.String(), nullable=True))
    op.add_column('releases', sa.Column('notified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'notified_at')
    op.drop_column('releases', 'url')
    # ### end Alembic commands ###
